### ISSUE TITLE
Exercise tracker

### ISSUE THREAD

**Issue by Arjun-Warrier** [Zubi-io/Project-Ideas#24]
**Before you start, please follow this format for your issue title**:  
Exercise tracker

## ℹ️ Project information
_Please complete all applicable._

- Excercise tracker
- **Short Project Description**: An excercise tracker app using MERN stack.
- **Any supporting Link**:
- **Labels**:MERN Full stack

## 🔥 Your Pitch
_Kindly write a detailed description for your project. Please do not use more than 500 words_

## 🔦 Looking for a help in?
_Can be Looking for teammates having skills in React.js or Looking for a mentor experienced in Data Structures to help me select optimised algorithm etc._ </br>

## ✅ Checklist

**Before you post the issue**:
- [ ] You have followed the issue title format.
- [ ] You have mentioned the correct labels.
- [ ] You have provided all the information correctly.
- [ ] Priority
  - [ ] **#1** : High
  - [ ] **#2** : Medium
  - [ ] **#3** : Low
- [ ] I understand that a reviewer will merge my pull request after examining it or ask for changes in case needed.
- [ ] I have [joined the telegram group](https://t.me/zubi_io).

**Comment by Arjun-Warrier** [comment]
https://github.com/Arjun-Warrier/excercise-tracker.git
